CREATE TABLE internet.`inforoom2_tickets` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Text` VARCHAR(255) NULL DEFAULT NULL,
	`Answer` VARCHAR(255) NULL DEFAULT NULL,
	`CreationDate` DATETIME NULL DEFAULT NULL,
	`AnswerDate` DATETIME NULL DEFAULT NULL,
	`IsPublished` TINYINT(1) NULL DEFAULT NULL,
	`Email` VARCHAR(255) NULL DEFAULT NULL,
	`Employee` INT(11) NULL DEFAULT NULL,
	`IsNotified` TINYINT(4) NOT NULL,
	PRIMARY KEY (`Id`),
	INDEX `Employee` (`Employee`),
	CONSTRAINT `FK962FBD596583FF54` FOREIGN KEY (`Employee`) REFERENCES internet.`inforoom2_employee` (`Id`)
)
COLLATE='cp1251_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6;