USE Internet;
CREATE TABLE `IpPoolRegions` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`IpPool` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`Region` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`)
)
COLLATE='cp1251_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=96;
