USE internet;
CREATE TABLE `inforoom2_Callmeback_Tickets` (
	`Employee` INT(10) UNSIGNED NULL DEFAULT NULL,
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NULL DEFAULT NULL,
	`Phone` VARCHAR(255) NOT NULL,
	`Text` VARCHAR(255) NULL DEFAULT NULL,
	`CreationDate` DATETIME NULL DEFAULT NULL,
	`AnswerDate` DATETIME NULL DEFAULT NULL,
	`Email` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`),
	INDEX `Employee` (`Employee`),
	CONSTRAINT FOREIGN KEY (`Employee`) REFERENCES `partners` (`Id`)
)
COLLATE='cp1251_general_ci'
ENGINE=InnoDB
