ALTER TABLE `Internet`.`clientendpoints`
 DROP FOREIGN KEY `FKBBAEFD19941C3747`;

ALTER TABLE `Internet`.`clientendpoints` ADD CONSTRAINT `FKBBAEFD19941C3747` FOREIGN KEY `FKBBAEFD19941C3747` (`Client`)
    REFERENCES `clients` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
