CREATE TABLE `internet`.`Orders` (
  `Id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `Number` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `BeginDate` DATETIME NOT NULL DEFAULT 0,
  `EndDate` DATETIME NOT NULL DEFAULT 0,
  `EndPoint` INTEGER UNSIGNED DEFAULT 0,
  `ClientId` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `Disabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`Id`),
  CONSTRAINT `FK_Orders_EndPoint` FOREIGN KEY `FK_Orders_EndPoint` (`EndPoint`)
    REFERENCES `clientendpoints` (`Id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
	 CONSTRAINT `FK_orders_client` FOREIGN KEY `FK_orders_client` (`ClientId`)
    REFERENCES `clients` (`Id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE `internet`.`OrderServices` (
  `Id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255),
  `Cost` DECIMAL NOT NULL DEFAULT 0,
  `IsPeriodic` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `OrderId` INTEGER UNSIGNED,
  PRIMARY KEY(`Id`),
  CONSTRAINT `FK_OrderServices_Order` FOREIGN KEY `FK_OrderServices_Order` (`OrderId`)
    REFERENCES `orders` (`Id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT
);
